apiVersion: 1

datasources:
  - name: Metrics PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: metrics
    user: metrics
    secureJsonData:
      password: 'metrics'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
      timescaledb: true
    editable: true
    isDefault: true
